text = ("My Daily Routine!")
print(text.title())
waking_up=input("At what time do you wake up?")
school=input("At what time do you go to school?")
play_time=input("How many hours did you play today?")
study=input("Did you study today?")
monhrs=input("how many hours did you study on monday?")
monhr_int = int(monhrs)
tueshrs = input("how many hours did you study on tuesday?")
tuehr_int= int(tueshrs)
wedhrs = input("how many hours did you study on wednesday?")
wedhr_int = int(wedhrs)
thuhrs = input("how many hours did you study on thursday?")
thuhr_int = int(thuhrs)
frihrs = input("how many hours did you study on friday?")
frihr_int = int(frihrs)
sathrs = input("how many hours did you study on saturday?")
sathr_int = int(sathrs)
sunhrs = input("how many hours did you study on sunday?")
sunhr_int = int(sunhrs)
print("your weekly study time is",monhr_int+tuehr_int+wedhr_int+thuhr_int+frihr_int+sathr_int+sunhr_int,"hours")
