import keyword
person_name=input("Enter your name.")
goal_name=input("Enter one skill you wanna be better at.")
target_month=input("Enter the month you wanna reach it by.")
daily_minutes=30
print("\n","My Personal Goal Plan","\n")
print("Name:",person_name)
print("Goal:",goal_name)
print("Target month:",target_month)
print("Daily practice:",daily_minutes)
print("Status:",end=" ")
print("Not Started")
print("Reminder",end="-")
print("Practice Everyday!")
print("In One Sentence:")
print(person_name,"plans to work on",goal_name,"for",daily_minutes,"minutes everyday until",target_month)
print(keyword.kwlist)